    global:
      scrape_interval: 5s
      scrape_timeout: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'tarantula.postoffice'
        metrics_path: /postoffice/metrics
        static_configs:
          - targets: ['postoffice:8000']
      - job_name: 'tarantula.presence'
        metrics_path: /presence/metrics
        static_configs:
          - targets: ['presence:8000']    
          